### Q3 A firm is starting a delivery service for a new client between 2 points. Since it is a new client, the firm wants to send more consistent delivery boy to deliver the product. Which delivery boy should they select? (Delivery Boy.xlsx). Solve this problem in Python.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import kurtosis, skew
df=pd.read_excel('Delivery Boy.xlsx')
df

deliveryboy1  deliveryboy2
0             12            40
1             13            10
2             17            31
3             21            59
4             24            13
5             24            50
6             26            27
7             27            33
8             27            53
9             30            34
10            32            16
11            35            10
12            37            34
13            38            30
14            41            33
15            43            42
16            44            34
17            46            44
18            53            29
19            60            28

In [2]:
print('The mean of delivery boy1 & 2 are:', df['deliveryboy1'].mean(),'&',df['deliveryboy2'].mean()),
print('The standard deviation of delivery boy1 & 2 are:',df['deliveryboy1'].std(),'&',df['deliveryboy2'].std()),
print('The variance of delivery boy1 & 2 are:',df['deliveryboy1'].var(),'&',df['deliveryboy2'].var())

## Since standard deviation of deliveryboy1 is less than deliveryboy2 so deliveryboy1 is more consistent,so firm will select
## deliveryboy1

The mean of delivery boy1 & 2 are: 32.5 & 32.5
The standard deviation of delivery boy1 & 2 are: 12.890224774488694 & 13.477076053334729
The variance of delivery boy1 & 2 are: 166.1578947368421 & 181.6315789473684


#### Mean same & variance unequal
#### Since standard deviation of deliveryboy1 is less than deliveryboy2 so deliveryboy1 is more consistent,so firm will select deliveryboy1

### Q4 Load Dataset ‘tips’ from Seaborn Library

In [3]:
dx=sns.load_dataset('tips')
dx

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Q5 Find the Correlation between ‘Total Bill’ column & ‘Tip’ column

In [4]:
np.corrcoef(dx['total_bill'],dx['tip'])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])

### Q6 Perform Two Sample t test between ‘sex’ column & ‘Tip’ column

In [5]:
dx_maletips=dx.loc[dx['sex']=='Male']
dx_maletips.mean()

total_bill    20.744076
tip            3.089618
size           2.630573
dtype: float64

In [6]:
dx_femaletips=dx.loc[dx['sex']=='Female']
dx_femaletips.mean()

total_bill    18.056897
tip            2.833448
size           2.459770
dtype: float64

#### Mean unequal

In [7]:
from sklearn import preprocessing 
import scipy.stats as stats
from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
from scipy.stats import chi2
label_encoder = preprocessing.LabelEncoder() 

dx['sex']= label_encoder.fit_transform(dx['sex']) 
  
dx['sex'].unique()

array([0, 1])

In [8]:
ttest,p_value=stats.ttest_ind(dx['tip'],dx['sex'],equal_var=True)
p_value

7.455763290496082e-90

In [9]:
## Mean value of male tips & female tips are different so we can reject null hypothesis
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypotesis


### Q7 Perform Chi Square Test between ‘sex’ column & ‘smoker’ column

In [10]:
dy=sns.load_dataset('tips')
dy

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
dy_table=pd.crosstab(dy['sex'],dy['smoker'])
dy_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [12]:
obs_values=dy_table.values
obs_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [13]:
val=stats.chi2_contingency(dy_table)
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [14]:
Expected_value=val[3]
Expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [15]:
no_of_rows=len(dy_table.iloc[0:2,0]) #Row Index, Column Index
no_of_rows

2

In [16]:
no_of_cols=len(dy_table.iloc[0,0:2]) #Row Index, Column Index
no_of_cols

2

In [17]:
ddof=(no_of_rows-1)*(no_of_cols-1)
ddof

1

In [18]:
chi_square=sum([(o-e)**2/e for o,e in zip(obs_values,Expected_value)])
chi_square

array([0.00119737, 0.00073745])

In [19]:
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

0.001934818536627623

In [20]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
p_value

0.964915107315732

In [21]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis')

Fail to reject Null Hypothesis


### Q9 A Business School have launched some mock interviews that claims that it will help students to get more job offers. School's record average of job offers received by students before and after the mock interview for 10 students for 24 weeks. Test the hypothesis that the student has a positive impact of mock interview with 95% confidence level. (Mock Interview.xlsx). Assume alpha=0.05

In [22]:
import pandas as pd
from sklearn import preprocessing 
import scipy.stats as stats
from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
from scipy.stats import chi2
df = pd.read_excel('Mock Interview.xlsx')
df

id  before  after
0   1       1      3
1   2       0      2
2   3       2      3
3   4       3      4
4   5       2      2
5   6       1      2
6   7       3      4
7   8       2      3
8   9       0      1
9  10       2      3

#### H0:  Mean of before = Mean of after  (No Difference), H1:  Mean of before != Mean of after  (There is a Difference)

In [23]:
df['before'].mean()

1.6

In [24]:
df['after'].mean()

2.7

In [25]:
ttest,p_value=stats.ttest_ind(df['before'],df['after'],equal_var=False)
p_value

0.026167287191718836

In [26]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypotesis


#### Since it rejects Null Hypothesis,So we accept all other hypothesis & so we can say that it has a positive impact of mock interviews  

### Q10 Honda Automotive is planning to launch three cars in a new state. The research team conducted a survey in the state to know the buying preferences of the people. They conduct a survey on random sample of people from urban, rural and semi urban areas. Now, Honda Automotive wants to know whether there is a specific preference for cars in different areas? (Honda.xlsx). Assume alpha = 0.05

In [27]:
import pandas as pd
from sklearn import preprocessing 
import scipy.stats as stats
from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
from scipy.stats import chi2
dc = pd.read_excel('Honda.xlsx')
dc

cartype areatype  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0    honda city    urban         NaN         NaN         NaN         NaN   
1    honda city    urban         NaN         NaN         NaN         NaN   
2    honda city    urban         NaN         NaN         NaN         NaN   
3    honda city    urban         NaN         NaN         NaN         NaN   
4    honda city    urban         NaN         NaN         NaN         NaN   
..          ...      ...         ...         ...         ...         ...   
321   honda crv    rural         NaN         NaN         NaN         NaN   
322   honda crv    rural         NaN         NaN         NaN         NaN   
323   honda crv    rural         NaN         NaN         NaN         NaN   
324   honda crv    rural         NaN         NaN         NaN         NaN   
325   honda crv    rural         NaN         NaN         NaN         NaN   

     Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  
0           NaN         NaN         NaN         NaN          NaN  
1           NaN         NaN         NaN         NaN          NaN  
2           NaN         NaN         NaN         NaN          NaN  
3           NaN         NaN         NaN         NaN          NaN  
4           NaN         NaN         NaN         NaN          NaN  
..          ...         ...         ...         ...          ...  
321         NaN         NaN         NaN         NaN          NaN  
322         NaN         NaN         NaN         NaN          NaN  
323         NaN         NaN         NaN         NaN          NaN  
324         NaN         NaN         NaN         NaN          NaN  
325         NaN         NaN         NaN         NaN          NaN  

[326 rows x 11 columns]

In [28]:
dc = dc.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8',
              'Unnamed: 9','Unnamed: 10'],axis=1)
dc

cartype areatype
0    honda city    urban
1    honda city    urban
2    honda city    urban
3    honda city    urban
4    honda city    urban
..          ...      ...
321   honda crv    rural
322   honda crv    rural
323   honda crv    rural
324   honda crv    rural
325   honda crv    rural

[326 rows x 2 columns]

In [29]:
dc_table=pd.crosstab(dc['cartype'],dc['areatype'])
dc_table

areatype      rural  semiurban  urban
cartype                              
honda accord     12         21     29
honda city       48         52     74
honda crv        39         34     17

In [30]:
obs_values=dc_table.values
obs_values

array([[12, 21, 29],
       [48, 52, 74],
       [39, 34, 17]], dtype=int64)

In [31]:
val=stats.chi2_contingency(dc_table)
val

(20.123744875840764,
 0.00047207713790297935,
 4,
 array([[18.82822086, 20.34969325, 22.82208589],
        [52.8404908 , 57.11042945, 64.04907975],
        [27.33128834, 29.5398773 , 33.12883436]]))

In [32]:
Expected_value=val[3]
Expected_value

array([[18.82822086, 20.34969325, 22.82208589],
       [52.8404908 , 57.11042945, 64.04907975],
       [27.33128834, 29.5398773 , 33.12883436]])

In [33]:
no_of_rows=len(dc_table.iloc[0:3,0])
no_of_rows

3

In [34]:
no_of_cols=len(dc_table.iloc[0,0:3]) 
no_of_cols

3

In [36]:
ddof=(no_of_rows-1)*(no_of_cols-1)
ddof

2

In [37]:
chi_square=sum([(o-e)**2/e for o,e in zip(obs_values,Expected_value)])
chi_square

array([ 7.9015247 ,  1.15149797, 11.0707222 ])

In [38]:
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

9.053022674217562

In [39]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
p_value

0.01081835189821545

In [40]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypotesis


#### Since it rejects Null Hypothesis,So we accept all other hypothesis & can say that there is a specific preference for cars in different areas

### Q8 Adidas sports recently launched discount schemes at their premium and best performing stores in Delhi, Mumbai and Bangalore. Now, the Analytics team wants to Analyze whether there is an impact of discounts and location on the sales. Do they need to keep different discount structure for different cities? (Adidas.xlsx)

In [43]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
da = pd.read_excel('Adidas .xlsx')
da

discount       city  sales
0        0.1      Delhi    133
1        0.1      Delhi    107
2        0.1      Delhi    114
3        0.1      Delhi    150
4        0.1      Delhi     85
5        0.2      Delhi    130
6        0.2      Delhi     86
7        0.2      Delhi    130
8        0.2      Delhi    112
9        0.2      Delhi    125
10       0.1     Mumbai     84
11       0.1     Mumbai    114
12       0.1     Mumbai    138
13       0.1     Mumbai    155
14       0.1     Mumbai     78
15       0.2     Mumbai    138
16       0.2     Mumbai    119
17       0.2     Mumbai    146
18       0.2     Mumbai    158
19       0.2     Mumbai    137
20       0.1  Bangalore     94
21       0.1  Bangalore    123
22       0.1  Bangalore    108
23       0.1  Bangalore    148
24       0.1  Bangalore     93
25       0.2  Bangalore    120
26       0.2  Bangalore    127
27       0.2  Bangalore    150
28       0.2  Bangalore    106
29       0.2  Bangalore    127

In [45]:
model = ols('sales ~ C(discount) + C(city) + C(discount):C(city)', data=da).fit()
sm.stats.anova_lm(model, typ=2)

sum_sq    df         F    PR(>F)
C(discount)           1165.633333   1.0  2.283168  0.143840
C(city)                488.066667   2.0  0.477997  0.625801
C(discount):C(city)    911.666667   2.0  0.892857  0.422654
Residual             12252.800000  24.0       NaN       NaN

#### Since P value of discount:location of sales is greater than 0.05, so we cannot reject null hypothesis & hence can say there is no impact of discounts and location on the sales. Hence there is no need to keep different discount structure for different cities.